import type { EditorThemeClasses } from 'lexical';

export const editorTheme: EditorThemeClasses = {
  paragraph: 'npc-editor-paragraph',
  quote: 'npc-editor-quote',
  heading: { h1: 'npc-editor-h1', h2: 'npc-editor-h2', h3: 'npc-editor-h3' },
  list: {
    ul: 'npc-editor-ul',
    ol: 'npc-editor-ol',
    listitem: 'npc-editor-li',
    listitemChecked: 'npc-editor-li-checked',
    listitemUnchecked: 'npc-editor-li-unchecked',
    nested: { listitem: 'npc-editor-li-nested' },
  },
  link: 'npc-editor-link',
  code: 'npc-editor-code-block',
  codeHighlight: {
    atrule: 'npc-code-atrule', attr: 'npc-code-attr', boolean: 'npc-code-boolean',
    builtin: 'npc-code-builtin', cdata: 'npc-code-cdata', char: 'npc-code-char',
    class: 'npc-code-class', 'class-name': 'npc-code-class-name', comment: 'npc-code-comment',
    constant: 'npc-code-constant', deleted: 'npc-code-deleted', doctype: 'npc-code-doctype',
    entity: 'npc-code-entity', function: 'npc-code-function', important: 'npc-code-important',
    inserted: 'npc-code-inserted', keyword: 'npc-code-keyword', namespace: 'npc-code-namespace',
    number: 'npc-code-number', operator: 'npc-code-operator', prolog: 'npc-code-prolog',
    property: 'npc-code-property', punctuation: 'npc-code-punctuation', regex: 'npc-code-regex',
    selector: 'npc-code-selector', string: 'npc-code-string', symbol: 'npc-code-symbol',
    tag: 'npc-code-tag', url: 'npc-code-url', variable: 'npc-code-variable',
  },
  text: {
    bold: 'npc-editor-bold',
    italic: 'npc-editor-italic',
    underline: 'npc-editor-underline',
    strikethrough: 'npc-editor-strikethrough',
    underlineStrikethrough: 'npc-editor-underline-strikethrough',
    code: 'npc-editor-inline-code',
    highlight: 'npc-editor-highlight',
    subscript: 'npc-editor-subscript',
    superscript: 'npc-editor-superscript',
  },
  table: 'npc-editor-table',
  tableCell: 'npc-editor-table-cell',
  tableCellHeader: 'npc-editor-table-cell-header',
  tableRow: 'npc-editor-table-row',
};
